from pathlib import Path
import json
r=Path(__file__).resolve().parents[1];a=r/'src/main/resources/assets/royalespells'
zh={'entity.royalespells.army_skeleton':'觉醒骷髅军团','entity.royalespells.dark_elixir_ritual':'暗黑重油觉醒仪式','spell.royalespells.skeleton_army_evolution':'皇室 · 觉醒骷髅军团','ironspell.royalespells.skeleton_army_evolution':'皇室 · 觉醒骷髅军团','instrument.royalespells.skeleton_army_horn':'骷髅将军的号角','item.royalespells.army_horn.effect':'吹响：召唤觉醒骷髅军团（不消耗法力）','message.royalespells.army_alive':'你的觉醒骷髅军团仍在场上，无法再次召唤','message.royalespells.army_cooldown':'觉醒骷髅军团与号角的共享冷却尚未结束','ui.royalespells.army_count':'召唤 15 名小骷髅与 1 名持盾骷髅将军，最多持续 10 分钟','ui.royalespells.army_general':'小骷髅阵亡化为幽灵；将军阵亡，军团消散','ui.royalespells.army_shared':'每人最多一支军团；卷轴、法术书与号角共享冷却'}
en={'entity.royalespells.army_skeleton':'Evolved Skeleton Army','entity.royalespells.dark_elixir_ritual':'Dark Elixir Awakening','spell.royalespells.skeleton_army_evolution':'Royale: Evolved Skeleton Army','ironspell.royalespells.skeleton_army_evolution':'Royale: Evolved Skeleton Army','instrument.royalespells.skeleton_army_horn':"General Gerry's Horn",'item.royalespells.army_horn.effect':'Blow: summon an Evolved Skeleton Army (no mana cost)','message.royalespells.army_alive':'Your Evolved Skeleton Army is still alive','message.royalespells.army_cooldown':'The army spell and horn are still on their shared cooldown','ui.royalespells.army_count':'Summons 15 Skeletons and 1 shielded General for up to 10 minutes','ui.royalespells.army_general':'Fallen Skeletons become ghosts; defeat the General to dispel his army','ui.royalespells.army_shared':'One army per player; scroll, spellbook and horn share a cooldown'}
for k,z,e in [('army_deploy','觉醒骷髅军团：号角齐鸣','Evolved Skeleton Army: deployment horn'),('army_horn','骷髅将军：吹响号角','General: horn'),('army_change','暗黑重油：灵魂觉醒','Dark elixir: awakening'),('army_death','骷髅将军：倒下','General: falls'),('skeleton_step','小骷髅：脚步','Skeleton: steps'),('skeleton_attack','小骷髅：挥剑','Skeleton: sword swing'),('skeleton_death','小骷髅：散架','Skeleton: falls')]:zh['subtitles.royalespells.'+k]=z;en['subtitles.royalespells.'+k]=e
for lang,extra in [('zh_cn',zh),('en_us',en)]:
 p=a/f'lang/{lang}.json';data=json.loads(p.read_text(encoding='utf-8'));data.update(extra);p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# Existing universal crafting tests cover the 29 craftable profiles. Ritual-only acquisition has its own integration tests.
p=r/'src/main/java/dev/royalespells/test/IronSpellSystemTests.java';s=p.read_text(encoding='utf-8')
s=s.replace('spell.isEnabled() && spell.allowCrafting() && pool.contains(spell)','spell.isEnabled() && (profile==IronSpellProfile.SKELETON_ARMY_EVOLUTION?!spell.allowCrafting() && !pool.contains(spell):spell.allowCrafting() && pool.contains(spell))')
s=s.replace('c.assertTrue(new SpellFilter(spell.getSchoolType()).getApplicableSpells().contains(spell),','c.assertTrue(profile==IronSpellProfile.SKELETON_ARMY_EVOLUTION?!new SpellFilter(spell.getSchoolType()).getApplicableSpells().contains(spell):new SpellFilter(spell.getSchoolType()).getApplicableSpells().contains(spell),')
s=s.replace('count==29','count==30').replace('All 28 spells and Barbarian Hut are registered','All 29 existing profiles and the ritual-only army are registered')
marker='public void forgeEverySpellWithItsNativeInkAndFocus';start=s.index(marker);end=s.index('@GameTest',start)
sub=s[start:end].replace('var spell=IronIntegration.spell(profile);','var spell=IronIntegration.spell(profile);if(!spell.allowCrafting())continue;');s=s[:start]+sub+s[end:]
s=s.replace('IronIntegration.scroll(profile,2));menu.createResult();','IronIntegration.scroll(profile,Math.min(2,profile.maxLevel())));menu.createResult();').replace('data(output).getLevel()==2,"Imbued spell and level retained"','data(output).getLevel()==Math.min(2,profile.maxLevel()),"Imbued spell and level retained"')
s=s.replace('if(profile==IronSpellProfile.MIRROR)continue;','if(profile==IronSpellProfile.MIRROR || profile==IronSpellProfile.SKELETON_ARMY_EVOLUTION)continue;')
p.write_text(s,encoding='utf-8')
p=r/'src/main/java/dev/royalespells/test/ElixirTests.java';s=p.read_text(encoding='utf-8').replace('if(spell.getMinRarity()>ink.grade)','if(!spell.allowCrafting() || spell.getMinRarity()>ink.grade)');p.write_text(s,encoding='utf-8')
